# Generated by Django 5.1 on 2024-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0002_alter_produto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
